### ISSUE TITLE
Validate > new group added after validation is not included in real-time validation 

### ISSUE THREAD

**Issue by mjbp** [stormid/components#138]
Repo steps:
- initialise instance of validate on form
- validate form in invalid state and see errors
- addGroup programatically
- observe real-time validation does not apply to new validation group

**Comment by sarah-storm** [comment]
Came across this today on a project.  It had it's own copy of the validation plugin, so I've resolved it there.  Will this still need rolled into the repo here or has it been picked up?

**Comment by mjbp** [comment]
@sarah-storm This hasn't been picked up yet in this repo, please PR your fix,

**Comment by mjbp** [comment]
Closed with [#182](https://github.com/stormid/components/pull/182) and published to npm in the latest @stormid/validate.
