### ISSUE TITLE
Group is removed if it contains hidden input. Other inputs cannot be validated.

### ISSUE THREAD

**Issue by sarah-storm** [stormid/components#159]
For .NET HTML Helper generated checkboxes, the markup generated uses a hidden input which contains a true/false value for the backend.

https://www.tutorialsteacher.com/mvc/htmlhelper-checkbox-checkboxfor

As these inputs are required to have the same name, the group as a whole ends up being removed from the validator, so the original checkbox cannot be validated.

**Comment by mjbp** [comment]
Closed by #160
