### ISSUE TITLE
Validate > revisit default error messages

### ISSUE THREAD

**Issue by mjbp** [stormid/components#184]
To my knowledge we have not used use default error messages very much, if at all, and certainly not in recent memory.

Can we remove them from the library, since they add a chunk of code, or should can we do something better with them?

This is also related to the issue/enhancement to be able to include the current field value in error mesasges.

**Comment by sarah-storm** [comment]
My thoughts on this would be that they're useful to have as a fall back so I'd prefer to keep them, but I've tended to be asked to override them in a project as they're a bit terse compared to current AX/Content design recommendations.  

Could we ask for advice from the rest of the team on a revised set of defaults?
