### ISSUE TITLE
Cookie banner > form submission message

### ISSUE THREAD

**Issue by mjbp** [stormid/components#224]
Issues: 
- the default message template has an incorrect aria-role attribute
- it is client-side rendered, so the message is not always announced even when the template is fixed

I think we should:
- correct the default message template - either with a valid role=alert, or no live region attribute
- add functionality that looks on the page for a server-rendered live region to use instead of the template

Questions/considerations:
- The client-side rendered inline confirmation message is useful (we couldn't position a server-rendered message container next to the button) so if we wanted to use a server-rendered message container for both visual and screen reader messages then the design would have to be different. 
- retain the current inline message, remove the role, use a server-rendered live region for the screen reader versus replace the design/behaviour?
- backwards compatibility with existing implementations that use the default config

Potential solutions:
- look for server-rendered container and save to state to be used in the messageTemplate render function
- update renderMessage and messageTemplate functions

**Comment by mjbp** [comment]
Great minds think alike! I started doing something like this on a branch of the UI Patterns on Friday. It has separate renderAnnouncement and renderMessage functions and has aria-hidden on the message  - https://github.com/stormid/components/tree/feature/cookie-banner-save-announcement/packages/cookie-banner

**Comment by mjbp** [comment]
@sarah-storm Test case at https://storm-ui-patterns.netlify.app/example/cookie-banner/form/
Tested on NVDA so far.

**Comment by sarah-storm** [comment]
No announcement on iOS so far…
https://user-images.githubusercontent.com/62299569/188721004-2183ce94-ec23-47ec-a6a5-0da317dbf70d.MOV

**Comment by sarah-storm** [comment]
Scratch that - downloaded the branch this morning to experiment, but it's announcing the message just fine now!   ¯\_(ツ)_/¯

https://user-images.githubusercontent.com/62299569/188842788-c8a4eca7-ed2f-439c-af86-cce3c521e248.MP4

**Comment by mjbp** [comment]
I have an iOS 12.5 device from the test lab and it is announced on that. Was just about to post a message but you beat me to iu.

**Comment by sarah-storm** [comment]
I've had it not announce since, but it's working 90% of the time now, and I can't quite narrow down what the difference is in the controls.  But it's almost certainly down to my amateur VO use!
